In [1]:
import numpy as np

In [2]:
#tICA-1 all trajectories load
p1 = np.loadtxt("Tica_Trajectories/Traj0_Tica0")
tica1_all_traj = p1.T
i = 1
while(i<=24):
    temp1 = np.loadtxt("Tica_Trajectories/Traj%d_Tica0"%i)
    temp1 = temp1.T
    tica1_all_traj = np.concatenate((tica1_all_traj,temp1))
    i = i+1



In [3]:
#tICA-2 all trajectories load
p2 = np.loadtxt("Tica_Trajectories/Traj0_Tica1")
tica2_all_traj = p2.T
i = 1
while(i<=24):
    temp2 = np.loadtxt("Tica_Trajectories/Traj%d_Tica1"%i)
    temp2 = temp2.T
    tica2_all_traj = np.concatenate((tica2_all_traj,temp2))
    i = i+1

In [4]:
#tICA-3 all trajectories load
p3 = np.loadtxt("Tica_Trajectories/Traj0_Tica2")
tica3_all_traj = p3.T
i = 1
while(i<=24):
    temp3 = np.loadtxt("Tica_Trajectories/Traj%d_Tica2"%i)
    temp3 = temp3.T
    tica3_all_traj = np.concatenate((tica3_all_traj,temp3))
    i = i+1

In [5]:
#tICA-4 all trajectories load
p4 = np.loadtxt("Tica_Trajectories/Traj0_Tica3")
tica4_all_traj = p4.T
i = 1
while(i<=24):
    temp4 = np.loadtxt("Tica_Trajectories/Traj%d_Tica3"%i)
    temp4 = temp4.T
    tica4_all_traj = np.concatenate((tica4_all_traj,temp4))
    i = i+1

In [6]:
#Phi
q2 = np.loadtxt("Dihedral/phi_2_Fr1")
q3 = np.loadtxt("Dihedral/phi_3_Fr1")
q4 = np.loadtxt("Dihedral/phi_4_Fr1")
q5 = np.loadtxt("Dihedral/phi_5_Fr1")
q6 = np.loadtxt("Dihedral/phi_6_Fr1")
q7 = np.loadtxt("Dihedral/phi_7_Fr1")
q8 = np.loadtxt("Dihedral/phi_8_Fr1")
q9 = np.loadtxt("Dihedral/phi_9_Fr1")
q10 = np.loadtxt("Dihedral/phi_10_Fr1")
phi2_all_traj = q2[:,1].T 
phi3_all_traj = q3[:,1].T
phi4_all_traj = q4[:,1].T
phi5_all_traj = q5[:,1].T
phi6_all_traj = q6[:,1].T
phi7_all_traj = q7[:,1].T
phi8_all_traj = q8[:,1].T
phi9_all_traj = q9[:,1].T
phi10_all_traj = q10[:,1].T
k1 = 2
while(k1<=6):
    tmp2 = np.loadtxt("Dihedral/phi_2_Fr%d"%k1)
    tmp3 = np.loadtxt("Dihedral/phi_3_Fr%d"%k1)
    tmp4 = np.loadtxt("Dihedral/phi_4_Fr%d"%k1)
    tmp5 = np.loadtxt("Dihedral/phi_5_Fr%d"%k1)
    tmp6 = np.loadtxt("Dihedral/phi_6_Fr%d"%k1)
    tmp7 = np.loadtxt("Dihedral/phi_7_Fr%d"%k1)
    tmp8 = np.loadtxt("Dihedral/phi_8_Fr%d"%k1)
    tmp9 = np.loadtxt("Dihedral/phi_9_Fr%d"%k1)
    tmp10 = np.loadtxt("Dihedral/phi_10_Fr%d"%k1)
    tmp2 = tmp2[:,1].T
    tmp3 = tmp3[:,1].T
    tmp4 = tmp4[:,1].T
    tmp5 = tmp5[:,1].T
    tmp6 = tmp6[:,1].T
    tmp7 = tmp7[:,1].T
    tmp8 = tmp8[:,1].T
    tmp9 = tmp9[:,1].T
    tmp10 = tmp10[:,1].T
    phi2_all_traj = np.concatenate((phi2_all_traj,tmp2))
    phi3_all_traj = np.concatenate((phi3_all_traj,tmp3))
    phi4_all_traj = np.concatenate((phi4_all_traj,tmp4))
    phi5_all_traj = np.concatenate((phi5_all_traj,tmp5))
    phi6_all_traj = np.concatenate((phi6_all_traj,tmp6))
    phi7_all_traj = np.concatenate((phi7_all_traj,tmp7))
    phi8_all_traj = np.concatenate((phi8_all_traj,tmp8))
    phi9_all_traj = np.concatenate((phi9_all_traj,tmp9))
    phi10_all_traj = np.concatenate((phi10_all_traj,tmp10))
    k1 = k1 +1
k2 = 8
while(k2<=25):
    g2 = np.loadtxt("Dihedral/phi_2_Fr%d"%k2)
    g3 = np.loadtxt("Dihedral/phi_3_Fr%d"%k2)
    g4 = np.loadtxt("Dihedral/phi_4_Fr%d"%k2)
    g5 = np.loadtxt("Dihedral/phi_5_Fr%d"%k2)
    g6 = np.loadtxt("Dihedral/phi_6_Fr%d"%k2)
    g7 = np.loadtxt("Dihedral/phi_7_Fr%d"%k2)
    g8 = np.loadtxt("Dihedral/phi_8_Fr%d"%k2)
    g9 = np.loadtxt("Dihedral/phi_9_Fr%d"%k2)
    g10 = np.loadtxt("Dihedral/phi_10_Fr%d"%k2)
    g2 = g2[:,1].T
    g3 = g3[:,1].T
    g4 = g4[:,1].T
    g5 = g5[:,1].T
    g6 = g6[:,1].T
    g7 = g7[:,1].T
    g8 = g8[:,1].T
    g9 = g9[:,1].T
    g10 = g10[:,1].T
    phi2_all_traj = np.concatenate((phi2_all_traj,g2))
    phi3_all_traj = np.concatenate((phi3_all_traj,g3))
    phi4_all_traj = np.concatenate((phi4_all_traj,g4))
    phi5_all_traj = np.concatenate((phi5_all_traj,g5))
    phi6_all_traj = np.concatenate((phi6_all_traj,g6))
    phi7_all_traj = np.concatenate((phi7_all_traj,g7))
    phi8_all_traj = np.concatenate((phi8_all_traj,g8))
    phi9_all_traj = np.concatenate((phi9_all_traj,g9))
    phi10_all_traj = np.concatenate((phi10_all_traj,g10))
    k2 = k2 +1
    
last2 = np.loadtxt("Dihedral/phi_2_Fr27")
last3 = np.loadtxt("Dihedral/phi_3_Fr27")
last4 = np.loadtxt("Dihedral/phi_4_Fr27")
last5 = np.loadtxt("Dihedral/phi_5_Fr27")
last6 = np.loadtxt("Dihedral/phi_6_Fr27")
last7 = np.loadtxt("Dihedral/phi_7_Fr27")
last8 = np.loadtxt("Dihedral/phi_8_Fr27")
last9 = np.loadtxt("Dihedral/phi_9_Fr27")
last10 = np.loadtxt("Dihedral/phi_10_Fr27")

last2 = last2[:,1].T
last3 = last3[:,1].T
last4 = last4[:,1].T
last5 = last5[:,1].T
last6 = last6[:,1].T
last7 = last7[:,1].T
last8 = last8[:,1].T
last9 = last9[:,1].T
last10 = last10[:,1].T

phi2_all_traj = np.concatenate((phi2_all_traj,last2))   
phi3_all_traj = np.concatenate((phi3_all_traj,last3))   
phi4_all_traj = np.concatenate((phi4_all_traj,last4))   
phi5_all_traj = np.concatenate((phi5_all_traj,last5))   
phi6_all_traj = np.concatenate((phi6_all_traj,last6))   
phi7_all_traj = np.concatenate((phi7_all_traj,last7))   
phi8_all_traj = np.concatenate((phi8_all_traj,last8))   
phi9_all_traj = np.concatenate((phi9_all_traj,last9))   
phi10_all_traj = np.concatenate((phi10_all_traj,last10)) 


        
    

In [7]:
phi2_all_traj_sin = np.sin(phi2_all_traj)
phi2_all_traj_cos = np.cos(phi2_all_traj)

phi3_all_traj_sin = np.sin(phi3_all_traj)
phi3_all_traj_cos = np.cos(phi3_all_traj)

phi4_all_traj_sin = np.sin(phi4_all_traj)
phi4_all_traj_cos = np.cos(phi4_all_traj)

phi5_all_traj_sin = np.sin(phi5_all_traj)
phi5_all_traj_cos = np.cos(phi5_all_traj)

phi6_all_traj_sin = np.sin(phi6_all_traj)
phi6_all_traj_cos = np.cos(phi6_all_traj)

phi7_all_traj_sin = np.sin(phi7_all_traj)
phi7_all_traj_cos = np.cos(phi7_all_traj)

phi8_all_traj_sin = np.sin(phi8_all_traj)
phi8_all_traj_cos = np.cos(phi8_all_traj)

phi9_all_traj_sin = np.sin(phi9_all_traj)
phi9_all_traj_cos = np.cos(phi9_all_traj)

phi10_all_traj_sin = np.sin(phi10_all_traj)
phi10_all_traj_cos = np.cos(phi10_all_traj)


In [8]:
tica1_CR_Phi2_sin = np.corrcoef(tica1_all_traj,phi2_all_traj_sin)
tica1_CR_Phi3_sin = np.corrcoef(tica1_all_traj,phi3_all_traj_sin)
tica1_CR_Phi4_sin = np.corrcoef(tica1_all_traj,phi4_all_traj_sin)
tica1_CR_Phi5_sin = np.corrcoef(tica1_all_traj,phi5_all_traj_sin)
tica1_CR_Phi6_sin = np.corrcoef(tica1_all_traj,phi6_all_traj_sin)
tica1_CR_Phi7_sin = np.corrcoef(tica1_all_traj,phi7_all_traj_sin)
tica1_CR_Phi8_sin = np.corrcoef(tica1_all_traj,phi8_all_traj_sin)
tica1_CR_Phi9_sin = np.corrcoef(tica1_all_traj,phi9_all_traj_sin)
tica1_CR_Phi10_sin = np.corrcoef(tica1_all_traj,phi10_all_traj_sin)

In [9]:
np.shape(tica1_all_traj)

(937500,)

In [10]:
np.shape(phi2_all_traj_sin)

(937500,)

In [11]:
tica1_CR_Phi2_cos = np.corrcoef(tica1_all_traj,phi2_all_traj_cos)
tica1_CR_Phi3_cos = np.corrcoef(tica1_all_traj,phi3_all_traj_cos)
tica1_CR_Phi4_cos = np.corrcoef(tica1_all_traj,phi4_all_traj_cos)
tica1_CR_Phi5_cos = np.corrcoef(tica1_all_traj,phi5_all_traj_cos)
tica1_CR_Phi6_cos = np.corrcoef(tica1_all_traj,phi6_all_traj_cos)
tica1_CR_Phi7_cos = np.corrcoef(tica1_all_traj,phi7_all_traj_cos)
tica1_CR_Phi8_cos = np.corrcoef(tica1_all_traj,phi8_all_traj_cos)
tica1_CR_Phi9_cos = np.corrcoef(tica1_all_traj,phi9_all_traj_cos)
tica1_CR_Phi10_cos = np.corrcoef(tica1_all_traj,phi10_all_traj_cos)

In [12]:
Correlation_Score_tica1 = np.zeros((9,1))
Correlation_Score_tica1[0,0] = np.abs(tica1_CR_Phi2_cos[0,1]) + np.abs(tica1_CR_Phi2_sin[0,1])
Correlation_Score_tica1[1,0] = np.abs(tica1_CR_Phi3_cos[0,1]) + np.abs(tica1_CR_Phi3_sin[0,1])
Correlation_Score_tica1[2,0] = np.abs(tica1_CR_Phi4_cos[0,1]) + np.abs(tica1_CR_Phi4_sin[0,1])
Correlation_Score_tica1[3,0] = np.abs(tica1_CR_Phi5_cos[0,1]) + np.abs(tica1_CR_Phi5_sin[0,1])
Correlation_Score_tica1[4,0] = np.abs(tica1_CR_Phi6_cos[0,1]) + np.abs(tica1_CR_Phi6_sin[0,1])
Correlation_Score_tica1[5,0] = np.abs(tica1_CR_Phi7_cos[0,1]) + np.abs(tica1_CR_Phi7_sin[0,1])
Correlation_Score_tica1[6,0] = np.abs(tica1_CR_Phi8_cos[0,1]) + np.abs(tica1_CR_Phi8_sin[0,1])
Correlation_Score_tica1[7,0] = np.abs(tica1_CR_Phi9_cos[0,1]) + np.abs(tica1_CR_Phi9_sin[0,1])
Correlation_Score_tica1[8,0] = np.abs(tica1_CR_Phi10_cos[0,1]) + np.abs(tica1_CR_Phi10_sin[0,1])

In [13]:
tica2_CR_Phi2_sin = np.corrcoef(tica2_all_traj,phi2_all_traj_sin)
tica2_CR_Phi3_sin = np.corrcoef(tica2_all_traj,phi3_all_traj_sin)
tica2_CR_Phi4_sin = np.corrcoef(tica2_all_traj,phi4_all_traj_sin)
tica2_CR_Phi5_sin = np.corrcoef(tica2_all_traj,phi5_all_traj_sin)
tica2_CR_Phi6_sin = np.corrcoef(tica2_all_traj,phi6_all_traj_sin)
tica2_CR_Phi7_sin = np.corrcoef(tica2_all_traj,phi7_all_traj_sin)
tica2_CR_Phi8_sin = np.corrcoef(tica2_all_traj,phi8_all_traj_sin)
tica2_CR_Phi9_sin = np.corrcoef(tica2_all_traj,phi9_all_traj_sin)
tica2_CR_Phi10_sin = np.corrcoef(tica2_all_traj,phi10_all_traj_sin)

In [14]:
tica2_CR_Phi2_cos = np.corrcoef(tica2_all_traj,phi2_all_traj_cos)
tica2_CR_Phi3_cos = np.corrcoef(tica2_all_traj,phi3_all_traj_cos)
tica2_CR_Phi4_cos = np.corrcoef(tica2_all_traj,phi4_all_traj_cos)
tica2_CR_Phi5_cos = np.corrcoef(tica2_all_traj,phi5_all_traj_cos)
tica2_CR_Phi6_cos = np.corrcoef(tica2_all_traj,phi6_all_traj_cos)
tica2_CR_Phi7_cos = np.corrcoef(tica2_all_traj,phi7_all_traj_cos)
tica2_CR_Phi8_cos = np.corrcoef(tica2_all_traj,phi8_all_traj_cos)
tica2_CR_Phi9_cos = np.corrcoef(tica2_all_traj,phi9_all_traj_cos)
tica2_CR_Phi10_cos = np.corrcoef(tica2_all_traj,phi10_all_traj_cos)

In [15]:
Correlation_Score_tica2 = np.zeros((9,1))
Correlation_Score_tica2[0,0] = np.abs(tica2_CR_Phi2_cos[0,1]) + np.abs(tica2_CR_Phi2_sin[0,1])
Correlation_Score_tica2[1,0] = np.abs(tica2_CR_Phi3_cos[0,1]) + np.abs(tica2_CR_Phi3_sin[0,1])
Correlation_Score_tica2[2,0] = np.abs(tica2_CR_Phi4_cos[0,1]) + np.abs(tica2_CR_Phi4_sin[0,1])
Correlation_Score_tica2[3,0] = np.abs(tica2_CR_Phi5_cos[0,1]) + np.abs(tica2_CR_Phi5_sin[0,1])
Correlation_Score_tica2[4,0] = np.abs(tica2_CR_Phi6_cos[0,1]) + np.abs(tica2_CR_Phi6_sin[0,1])
Correlation_Score_tica2[5,0] = np.abs(tica2_CR_Phi7_cos[0,1]) + np.abs(tica2_CR_Phi7_sin[0,1])
Correlation_Score_tica2[6,0] = np.abs(tica2_CR_Phi8_cos[0,1]) + np.abs(tica2_CR_Phi8_sin[0,1])
Correlation_Score_tica2[7,0] = np.abs(tica2_CR_Phi9_cos[0,1]) + np.abs(tica2_CR_Phi9_sin[0,1])
Correlation_Score_tica2[8,0] = np.abs(tica2_CR_Phi10_cos[0,1]) + np.abs(tica2_CR_Phi10_sin[0,1])

In [16]:
tica3_CR_Phi2_sin = np.corrcoef(tica3_all_traj,phi2_all_traj_sin)
tica3_CR_Phi3_sin = np.corrcoef(tica3_all_traj,phi3_all_traj_sin)
tica3_CR_Phi4_sin = np.corrcoef(tica3_all_traj,phi4_all_traj_sin)
tica3_CR_Phi5_sin = np.corrcoef(tica3_all_traj,phi5_all_traj_sin)
tica3_CR_Phi6_sin = np.corrcoef(tica3_all_traj,phi6_all_traj_sin)
tica3_CR_Phi7_sin = np.corrcoef(tica3_all_traj,phi7_all_traj_sin)
tica3_CR_Phi8_sin = np.corrcoef(tica3_all_traj,phi8_all_traj_sin)
tica3_CR_Phi9_sin = np.corrcoef(tica3_all_traj,phi9_all_traj_sin)
tica3_CR_Phi10_sin = np.corrcoef(tica3_all_traj,phi10_all_traj_sin)

In [17]:
tica3_CR_Phi2_cos = np.corrcoef(tica3_all_traj,phi2_all_traj_cos)
tica3_CR_Phi3_cos = np.corrcoef(tica3_all_traj,phi3_all_traj_cos)
tica3_CR_Phi4_cos = np.corrcoef(tica3_all_traj,phi4_all_traj_cos)
tica3_CR_Phi5_cos = np.corrcoef(tica3_all_traj,phi5_all_traj_cos)
tica3_CR_Phi6_cos = np.corrcoef(tica3_all_traj,phi6_all_traj_cos)
tica3_CR_Phi7_cos = np.corrcoef(tica3_all_traj,phi7_all_traj_cos)
tica3_CR_Phi8_cos = np.corrcoef(tica3_all_traj,phi8_all_traj_cos)
tica3_CR_Phi9_cos = np.corrcoef(tica3_all_traj,phi9_all_traj_cos)
tica3_CR_Phi10_cos = np.corrcoef(tica3_all_traj,phi10_all_traj_cos)

In [18]:
Correlation_Score_tica3 = np.zeros((9,1))
Correlation_Score_tica3[0,0] = np.abs(tica3_CR_Phi2_cos[0,1]) + np.abs(tica3_CR_Phi2_sin[0,1])
Correlation_Score_tica3[1,0] = np.abs(tica3_CR_Phi3_cos[0,1]) + np.abs(tica3_CR_Phi3_sin[0,1])
Correlation_Score_tica3[2,0] = np.abs(tica3_CR_Phi4_cos[0,1]) + np.abs(tica3_CR_Phi4_sin[0,1])
Correlation_Score_tica3[3,0] = np.abs(tica3_CR_Phi5_cos[0,1]) + np.abs(tica3_CR_Phi5_sin[0,1])
Correlation_Score_tica3[4,0] = np.abs(tica3_CR_Phi6_cos[0,1]) + np.abs(tica3_CR_Phi6_sin[0,1])
Correlation_Score_tica3[5,0] = np.abs(tica3_CR_Phi7_cos[0,1]) + np.abs(tica3_CR_Phi7_sin[0,1])
Correlation_Score_tica3[6,0] = np.abs(tica3_CR_Phi8_cos[0,1]) + np.abs(tica3_CR_Phi8_sin[0,1])
Correlation_Score_tica3[7,0] = np.abs(tica3_CR_Phi9_cos[0,1]) + np.abs(tica3_CR_Phi9_sin[0,1])
Correlation_Score_tica3[8,0] = np.abs(tica3_CR_Phi10_cos[0,1]) + np.abs(tica3_CR_Phi10_sin[0,1])

In [19]:
tica4_CR_Phi2_sin = np.corrcoef(tica4_all_traj,phi2_all_traj_sin)
tica4_CR_Phi3_sin = np.corrcoef(tica4_all_traj,phi3_all_traj_sin)
tica4_CR_Phi4_sin = np.corrcoef(tica4_all_traj,phi4_all_traj_sin)
tica4_CR_Phi5_sin = np.corrcoef(tica4_all_traj,phi5_all_traj_sin)
tica4_CR_Phi6_sin = np.corrcoef(tica4_all_traj,phi6_all_traj_sin)
tica4_CR_Phi7_sin = np.corrcoef(tica4_all_traj,phi7_all_traj_sin)
tica4_CR_Phi8_sin = np.corrcoef(tica4_all_traj,phi8_all_traj_sin)
tica4_CR_Phi9_sin = np.corrcoef(tica4_all_traj,phi9_all_traj_sin)
tica4_CR_Phi10_sin = np.corrcoef(tica4_all_traj,phi10_all_traj_sin)

In [20]:
tica4_CR_Phi2_cos = np.corrcoef(tica4_all_traj,phi2_all_traj_cos)
tica4_CR_Phi3_cos = np.corrcoef(tica4_all_traj,phi3_all_traj_cos)
tica4_CR_Phi4_cos = np.corrcoef(tica4_all_traj,phi4_all_traj_cos)
tica4_CR_Phi5_cos = np.corrcoef(tica4_all_traj,phi5_all_traj_cos)
tica4_CR_Phi6_cos = np.corrcoef(tica4_all_traj,phi6_all_traj_cos)
tica4_CR_Phi7_cos = np.corrcoef(tica4_all_traj,phi7_all_traj_cos)
tica4_CR_Phi8_cos = np.corrcoef(tica4_all_traj,phi8_all_traj_cos)
tica4_CR_Phi9_cos = np.corrcoef(tica4_all_traj,phi9_all_traj_cos)
tica4_CR_Phi10_cos = np.corrcoef(tica4_all_traj,phi10_all_traj_cos)

In [21]:
Correlation_Score_tica4 = np.zeros((9,1))
Correlation_Score_tica4[0,0] = np.abs(tica4_CR_Phi2_cos[0,1]) + np.abs(tica4_CR_Phi2_sin[0,1])
Correlation_Score_tica4[1,0] = np.abs(tica4_CR_Phi3_cos[0,1]) + np.abs(tica4_CR_Phi3_sin[0,1])
Correlation_Score_tica4[2,0] = np.abs(tica4_CR_Phi4_cos[0,1]) + np.abs(tica4_CR_Phi4_sin[0,1])
Correlation_Score_tica4[3,0] = np.abs(tica4_CR_Phi5_cos[0,1]) + np.abs(tica4_CR_Phi5_sin[0,1])
Correlation_Score_tica4[4,0] = np.abs(tica4_CR_Phi6_cos[0,1]) + np.abs(tica4_CR_Phi6_sin[0,1])
Correlation_Score_tica4[5,0] = np.abs(tica4_CR_Phi7_cos[0,1]) + np.abs(tica4_CR_Phi7_sin[0,1])
Correlation_Score_tica4[6,0] = np.abs(tica4_CR_Phi8_cos[0,1]) + np.abs(tica4_CR_Phi8_sin[0,1])
Correlation_Score_tica4[7,0] = np.abs(tica4_CR_Phi9_cos[0,1]) + np.abs(tica4_CR_Phi9_sin[0,1])
Correlation_Score_tica4[8,0] = np.abs(tica4_CR_Phi10_cos[0,1]) + np.abs(tica4_CR_Phi10_sin[0,1])

In [22]:
print(Correlation_Score_tica1)

[[0.07957825]
 [0.27762882]
 [0.54981   ]
 [0.27285276]
 [0.09085925]
 [0.14262957]
 [0.09161211]
 [0.03654911]
 [0.06742381]]


In [23]:
print(Correlation_Score_tica2)

[[0.13263962]
 [0.14412192]
 [0.02797656]
 [0.46871743]
 [0.03028227]
 [0.15939843]
 [0.17843882]
 [0.07108712]
 [0.05700685]]


In [23]:
delta_delta_F = [ 1.4318905 , -9.05675749, -2.76302572, -3.60076012, -0.03739514,
        2.00005859, -1.18727246, -6.79608942, -5.44399137, -1.3625668 ,
        0.8025274 ]
CS_phi = [ 0.06437967, 0.24489582, 0.5014504,  0.27972149, 0.02369518, 0.1708882, 0.1708882,
        0.07400696, 0.02587254, 0.06086136]
CS_psi = [0.26977169, 0.26953212, 0.0897338,  1.07754125, 0.87940289, 0.58528877,
 0.27776795, 0.27776795, 0.02737757, 0.06349432]



In [27]:
print(Correlation_Score_tica2)

[[0.15232324]
 [0.11675481]
 [0.08069406]
 [0.36525409]
 [0.14311466]
 [0.22015174]
 [0.08083921]
 [0.03702179]
 [0.01684373]]


In [28]:
print(Correlation_Score_tica3)

[[0.22538355]
 [0.18896156]
 [0.15117724]
 [0.06926   ]
 [0.13627033]
 [0.08553722]
 [0.01884736]
 [0.04349681]
 [0.01192223]]


In [29]:
print(Correlation_Score_tica4)

[[0.08902001]
 [0.05760653]
 [0.14779002]
 [0.10024028]
 [0.06456111]
 [0.19266405]
 [0.29103117]
 [0.23357321]
 [0.14068451]]


In [30]:
#Si
r1 = np.loadtxt("Dihedral/psi_1_Fr1")
r2 = np.loadtxt("Dihedral/psi_2_Fr1")
r3 = np.loadtxt("Dihedral/psi_3_Fr1")
r4 = np.loadtxt("Dihedral/psi_4_Fr1")
r5 = np.loadtxt("Dihedral/psi_5_Fr1")
r6 = np.loadtxt("Dihedral/psi_6_Fr1")
r7 = np.loadtxt("Dihedral/psi_7_Fr1")
r8 = np.loadtxt("Dihedral/psi_8_Fr1")
r9 = np.loadtxt("Dihedral/psi_9_Fr1")
si1_all_traj = r1[:,1].T 
si2_all_traj = r2[:,1].T
si3_all_traj = r3[:,1].T
si4_all_traj = r4[:,1].T
si5_all_traj = r5[:,1].T
si6_all_traj = r6[:,1].T
si7_all_traj = r7[:,1].T
si8_all_traj = r8[:,1].T
si9_all_traj = r9[:,1].T
k1 = 2
while(k1<=6):
    tmp1 = np.loadtxt("Dihedral/psi_1_Fr%d"%k1)
    tmp2 = np.loadtxt("Dihedral/psi_2_Fr%d"%k1)
    tmp3 = np.loadtxt("Dihedral/psi_3_Fr%d"%k1)
    tmp4 = np.loadtxt("Dihedral/psi_4_Fr%d"%k1)
    tmp5 = np.loadtxt("Dihedral/psi_5_Fr%d"%k1)
    tmp6 = np.loadtxt("Dihedral/psi_6_Fr%d"%k1)
    tmp7 = np.loadtxt("Dihedral/psi_7_Fr%d"%k1)
    tmp8 = np.loadtxt("Dihedral/psi_8_Fr%d"%k1)
    tmp9 = np.loadtxt("Dihedral/psi_9_Fr%d"%k1)
    tmp1 = tmp1[:,1].T
    tmp2 = tmp2[:,1].T
    tmp3 = tmp3[:,1].T
    tmp4 = tmp4[:,1].T
    tmp5 = tmp5[:,1].T
    tmp6 = tmp6[:,1].T
    tmp7 = tmp7[:,1].T
    tmp8 = tmp8[:,1].T
    tmp9 = tmp9[:,1].T
    si1_all_traj = np.concatenate((si1_all_traj,tmp1))
    si2_all_traj = np.concatenate((si2_all_traj,tmp2))
    si3_all_traj = np.concatenate((si3_all_traj,tmp3))
    si4_all_traj = np.concatenate((si4_all_traj,tmp4))
    si5_all_traj = np.concatenate((si5_all_traj,tmp5))
    si6_all_traj = np.concatenate((si6_all_traj,tmp6))
    si7_all_traj = np.concatenate((si7_all_traj,tmp7))
    si8_all_traj = np.concatenate((si8_all_traj,tmp8))
    si9_all_traj = np.concatenate((si9_all_traj,tmp9))
    k1 = k1 +1
k2 = 8
while(k2<=25):
    g1 = np.loadtxt("Dihedral/psi_1_Fr%d"%k2)
    g2 = np.loadtxt("Dihedral/psi_2_Fr%d"%k2)
    g3 = np.loadtxt("Dihedral/psi_3_Fr%d"%k2)
    g4 = np.loadtxt("Dihedral/psi_4_Fr%d"%k2)
    g5 = np.loadtxt("Dihedral/psi_5_Fr%d"%k2)
    g6 = np.loadtxt("Dihedral/psi_6_Fr%d"%k2)
    g7 = np.loadtxt("Dihedral/psi_7_Fr%d"%k2)
    g8 = np.loadtxt("Dihedral/psi_8_Fr%d"%k2)
    g9 = np.loadtxt("Dihedral/psi_9_Fr%d"%k2)
    g1 = g2[:,1].T
    g2 = g2[:,1].T
    g3 = g3[:,1].T
    g4 = g4[:,1].T
    g5 = g5[:,1].T
    g6 = g6[:,1].T
    g7 = g7[:,1].T
    g8 = g8[:,1].T
    g9 = g9[:,1].T
    si1_all_traj = np.concatenate((si1_all_traj,g1))
    si2_all_traj = np.concatenate((si2_all_traj,g2))
    si3_all_traj = np.concatenate((si3_all_traj,g3))
    si4_all_traj = np.concatenate((si4_all_traj,g4))
    si5_all_traj = np.concatenate((si5_all_traj,g5))
    si6_all_traj = np.concatenate((si6_all_traj,g6))
    si7_all_traj = np.concatenate((si7_all_traj,g7))
    si8_all_traj = np.concatenate((si8_all_traj,g8))
    si9_all_traj = np.concatenate((si9_all_traj,g9)) 
    k2 = k2 +1
last1 = np.loadtxt("Dihedral/psi_1_Fr27")    
last2 = np.loadtxt("Dihedral/psi_2_Fr27")
last3 = np.loadtxt("Dihedral/psi_3_Fr27")
last4 = np.loadtxt("Dihedral/psi_4_Fr27")
last5 = np.loadtxt("Dihedral/psi_5_Fr27")
last6 = np.loadtxt("Dihedral/psi_6_Fr27")
last7 = np.loadtxt("Dihedral/psi_7_Fr27")
last8 = np.loadtxt("Dihedral/psi_8_Fr27")
last9 = np.loadtxt("Dihedral/psi_9_Fr27")

last1 = last1[:,1].T
last2 = last2[:,1].T
last3 = last3[:,1].T
last4 = last4[:,1].T
last5 = last5[:,1].T
last6 = last6[:,1].T
last7 = last7[:,1].T
last8 = last8[:,1].T
last9 = last9[:,1].T

si1_all_traj = np.concatenate((si1_all_traj,last1))
si2_all_traj = np.concatenate((si2_all_traj,last2))   
si3_all_traj = np.concatenate((si3_all_traj,last3))   
si4_all_traj = np.concatenate((si4_all_traj,last4))   
si5_all_traj = np.concatenate((si5_all_traj,last5))   
si6_all_traj = np.concatenate((si6_all_traj,last6))   
si7_all_traj = np.concatenate((si7_all_traj,last7))   
si8_all_traj = np.concatenate((si8_all_traj,last8))   
si9_all_traj = np.concatenate((si9_all_traj,last9))   
 


        
    

In [31]:
si1_all_traj_sin = np.sin(si1_all_traj)
si1_all_traj_cos = np.cos(si1_all_traj)

si2_all_traj_sin = np.sin(si2_all_traj)
si2_all_traj_cos = np.cos(si2_all_traj)

si3_all_traj_sin = np.sin(si3_all_traj)
si3_all_traj_cos = np.cos(si3_all_traj)

si4_all_traj_sin = np.sin(si4_all_traj)
si4_all_traj_cos = np.cos(si4_all_traj)

si5_all_traj_sin = np.sin(si5_all_traj)
si5_all_traj_cos = np.cos(si5_all_traj)

si6_all_traj_sin = np.sin(si6_all_traj)
si6_all_traj_cos = np.cos(si6_all_traj)

si7_all_traj_sin = np.sin(si7_all_traj)
si7_all_traj_cos = np.cos(si7_all_traj)

si8_all_traj_sin = np.sin(si8_all_traj)
si8_all_traj_cos = np.cos(si8_all_traj)

si9_all_traj_sin = np.sin(si9_all_traj)
si9_all_traj_cos = np.cos(si9_all_traj)




In [32]:
tica1_CR_si1_sin = np.corrcoef(tica1_all_traj,si1_all_traj_sin)
tica1_CR_si2_sin = np.corrcoef(tica1_all_traj,si2_all_traj_sin)
tica1_CR_si3_sin = np.corrcoef(tica1_all_traj,si3_all_traj_sin)
tica1_CR_si4_sin = np.corrcoef(tica1_all_traj,si4_all_traj_sin)
tica1_CR_si5_sin = np.corrcoef(tica1_all_traj,si5_all_traj_sin)
tica1_CR_si6_sin = np.corrcoef(tica1_all_traj,si6_all_traj_sin)
tica1_CR_si7_sin = np.corrcoef(tica1_all_traj,si7_all_traj_sin)
tica1_CR_si8_sin = np.corrcoef(tica1_all_traj,si8_all_traj_sin)
tica1_CR_si9_sin = np.corrcoef(tica1_all_traj,si9_all_traj_sin)

tica1_CR_si1_cos = np.corrcoef(tica1_all_traj,si1_all_traj_cos)
tica1_CR_si2_cos = np.corrcoef(tica1_all_traj,si2_all_traj_cos)
tica1_CR_si3_cos = np.corrcoef(tica1_all_traj,si3_all_traj_cos)
tica1_CR_si4_cos = np.corrcoef(tica1_all_traj,si4_all_traj_cos)
tica1_CR_si5_cos = np.corrcoef(tica1_all_traj,si5_all_traj_cos)
tica1_CR_si6_cos = np.corrcoef(tica1_all_traj,si6_all_traj_cos)
tica1_CR_si7_cos = np.corrcoef(tica1_all_traj,si7_all_traj_cos)
tica1_CR_si8_cos = np.corrcoef(tica1_all_traj,si8_all_traj_cos)
tica1_CR_si9_cos = np.corrcoef(tica1_all_traj,si9_all_traj_cos)


Correlation_Score_tica1_si = np.zeros((9,1))
Correlation_Score_tica1_si[0,0] = np.abs(tica1_CR_si1_cos[0,1]) + np.abs(tica1_CR_si1_sin[0,1])
Correlation_Score_tica1_si[1,0] = np.abs(tica1_CR_si2_cos[0,1]) + np.abs(tica1_CR_si2_sin[0,1])
Correlation_Score_tica1_si[2,0] = np.abs(tica1_CR_si3_cos[0,1]) + np.abs(tica1_CR_si3_sin[0,1])
Correlation_Score_tica1_si[3,0] = np.abs(tica1_CR_si4_cos[0,1]) + np.abs(tica1_CR_si4_sin[0,1])
Correlation_Score_tica1_si[4,0] = np.abs(tica1_CR_si5_cos[0,1]) + np.abs(tica1_CR_si5_sin[0,1])
Correlation_Score_tica1_si[5,0] = np.abs(tica1_CR_si6_cos[0,1]) + np.abs(tica1_CR_si6_sin[0,1])
Correlation_Score_tica1_si[6,0] = np.abs(tica1_CR_si7_cos[0,1]) + np.abs(tica1_CR_si7_sin[0,1])
Correlation_Score_tica1_si[7,0] = np.abs(tica1_CR_si8_cos[0,1]) + np.abs(tica1_CR_si8_sin[0,1])
Correlation_Score_tica1_si[8,0] = np.abs(tica1_CR_si9_cos[0,1]) + np.abs(tica1_CR_si9_sin[0,1])

In [33]:
tica2_CR_si1_sin = np.corrcoef(tica2_all_traj,si1_all_traj_sin)
tica2_CR_si2_sin = np.corrcoef(tica2_all_traj,si2_all_traj_sin)
tica2_CR_si3_sin = np.corrcoef(tica2_all_traj,si3_all_traj_sin)
tica2_CR_si4_sin = np.corrcoef(tica2_all_traj,si4_all_traj_sin)
tica2_CR_si5_sin = np.corrcoef(tica2_all_traj,si5_all_traj_sin)
tica2_CR_si6_sin = np.corrcoef(tica2_all_traj,si6_all_traj_sin)
tica2_CR_si7_sin = np.corrcoef(tica2_all_traj,si7_all_traj_sin)
tica2_CR_si8_sin = np.corrcoef(tica2_all_traj,si8_all_traj_sin)
tica2_CR_si9_sin = np.corrcoef(tica2_all_traj,si9_all_traj_sin)

tica2_CR_si1_cos = np.corrcoef(tica2_all_traj,si1_all_traj_cos)
tica2_CR_si2_cos = np.corrcoef(tica2_all_traj,si2_all_traj_cos)
tica2_CR_si3_cos = np.corrcoef(tica2_all_traj,si3_all_traj_cos)
tica2_CR_si4_cos = np.corrcoef(tica2_all_traj,si4_all_traj_cos)
tica2_CR_si5_cos = np.corrcoef(tica2_all_traj,si5_all_traj_cos)
tica2_CR_si6_cos = np.corrcoef(tica2_all_traj,si6_all_traj_cos)
tica2_CR_si7_cos = np.corrcoef(tica2_all_traj,si7_all_traj_cos)
tica2_CR_si8_cos = np.corrcoef(tica2_all_traj,si8_all_traj_cos)
tica2_CR_si9_cos = np.corrcoef(tica2_all_traj,si9_all_traj_cos)


Correlation_Score_tica2_si = np.zeros((9,1))
Correlation_Score_tica2_si[0,0] = np.abs(tica2_CR_si1_cos[0,1]) + np.abs(tica2_CR_si1_sin[0,1])
Correlation_Score_tica2_si[1,0] = np.abs(tica2_CR_si2_cos[0,1]) + np.abs(tica2_CR_si2_sin[0,1])
Correlation_Score_tica2_si[2,0] = np.abs(tica2_CR_si3_cos[0,1]) + np.abs(tica2_CR_si3_sin[0,1])
Correlation_Score_tica2_si[3,0] = np.abs(tica2_CR_si4_cos[0,1]) + np.abs(tica2_CR_si4_sin[0,1])
Correlation_Score_tica2_si[4,0] = np.abs(tica2_CR_si5_cos[0,1]) + np.abs(tica2_CR_si5_sin[0,1])
Correlation_Score_tica2_si[5,0] = np.abs(tica2_CR_si6_cos[0,1]) + np.abs(tica2_CR_si6_sin[0,1])
Correlation_Score_tica2_si[6,0] = np.abs(tica2_CR_si7_cos[0,1]) + np.abs(tica2_CR_si7_sin[0,1])
Correlation_Score_tica2_si[7,0] = np.abs(tica2_CR_si8_cos[0,1]) + np.abs(tica2_CR_si8_sin[0,1])
Correlation_Score_tica2_si[8,0] = np.abs(tica2_CR_si9_cos[0,1]) + np.abs(tica2_CR_si9_sin[0,1])

In [ ]:
tica3_CR_si1_sin = np.corrcoef(tica3_all_traj,si1_all_traj_sin)
tica3_CR_si2_sin = np.corrcoef(tica3_all_traj,si2_all_traj_sin)
tica3_CR_si3_sin = np.corrcoef(tica3_all_traj,si3_all_traj_sin)
tica3_CR_si4_sin = np.corrcoef(tica3_all_traj,si4_all_traj_sin)
tica3_CR_si5_sin = np.corrcoef(tica3_all_traj,si5_all_traj_sin)
tica3_CR_si6_sin = np.corrcoef(tica3_all_traj,si6_all_traj_sin)
tica3_CR_si7_sin = np.corrcoef(tica3_all_traj,si7_all_traj_sin)
tica3_CR_si8_sin = np.corrcoef(tica3_all_traj,si8_all_traj_sin)
tica3_CR_si9_sin = np.corrcoef(tica3_all_traj,si9_all_traj_sin)

tica3_CR_si1_cos = np.corrcoef(tica3_all_traj,si1_all_traj_cos)
tica3_CR_si2_cos = np.corrcoef(tica3_all_traj,si2_all_traj_cos)
tica3_CR_si3_cos = np.corrcoef(tica3_all_traj,si3_all_traj_cos)
tica3_CR_si4_cos = np.corrcoef(tica3_all_traj,si4_all_traj_cos)
tica3_CR_si5_cos = np.corrcoef(tica3_all_traj,si5_all_traj_cos)
tica3_CR_si6_cos = np.corrcoef(tica3_all_traj,si6_all_traj_cos)
tica3_CR_si7_cos = np.corrcoef(tica3_all_traj,si7_all_traj_cos)
tica3_CR_si8_cos = np.corrcoef(tica3_all_traj,si8_all_traj_cos)
tica3_CR_si9_cos = np.corrcoef(tica3_all_traj,si9_all_traj_cos)


Correlation_Score_tica3_si = np.zeros((9,1))
Correlation_Score_tica3_si[0,0] = np.abs(tica3_CR_si1_cos[0,1]) + np.abs(tica3_CR_si1_sin[0,1])
Correlation_Score_tica3_si[1,0] = np.abs(tica3_CR_si2_cos[0,1]) + np.abs(tica3_CR_si2_sin[0,1])
Correlation_Score_tica3_si[2,0] = np.abs(tica3_CR_si3_cos[0,1]) + np.abs(tica3_CR_si3_sin[0,1])
Correlation_Score_tica3_si[3,0] = np.abs(tica3_CR_si4_cos[0,1]) + np.abs(tica3_CR_si4_sin[0,1])
Correlation_Score_tica3_si[4,0] = np.abs(tica3_CR_si5_cos[0,1]) + np.abs(tica3_CR_si5_sin[0,1])
Correlation_Score_tica3_si[5,0] = np.abs(tica3_CR_si6_cos[0,1]) + np.abs(tica3_CR_si6_sin[0,1])
Correlation_Score_tica3_si[6,0] = np.abs(tica3_CR_si7_cos[0,1]) + np.abs(tica3_CR_si7_sin[0,1])
Correlation_Score_tica3_si[7,0] = np.abs(tica3_CR_si8_cos[0,1]) + np.abs(tica3_CR_si8_sin[0,1])
Correlation_Score_tica3_si[8,0] = np.abs(tica3_CR_si9_cos[0,1]) + np.abs(tica3_CR_si9_sin[0,1])

In [34]:
tica4_CR_si1_sin = np.corrcoef(tica4_all_traj,si1_all_traj_sin)
tica4_CR_si2_sin = np.corrcoef(tica4_all_traj,si2_all_traj_sin)
tica4_CR_si3_sin = np.corrcoef(tica4_all_traj,si3_all_traj_sin)
tica4_CR_si4_sin = np.corrcoef(tica4_all_traj,si4_all_traj_sin)
tica4_CR_si5_sin = np.corrcoef(tica4_all_traj,si5_all_traj_sin)
tica4_CR_si6_sin = np.corrcoef(tica4_all_traj,si6_all_traj_sin)
tica4_CR_si7_sin = np.corrcoef(tica4_all_traj,si7_all_traj_sin)
tica4_CR_si8_sin = np.corrcoef(tica4_all_traj,si8_all_traj_sin)
tica4_CR_si9_sin = np.corrcoef(tica4_all_traj,si9_all_traj_sin)

tica4_CR_si1_cos = np.corrcoef(tica4_all_traj,si1_all_traj_cos)
tica4_CR_si2_cos = np.corrcoef(tica4_all_traj,si2_all_traj_cos)
tica4_CR_si3_cos = np.corrcoef(tica4_all_traj,si3_all_traj_cos)
tica4_CR_si4_cos = np.corrcoef(tica4_all_traj,si4_all_traj_cos)
tica4_CR_si5_cos = np.corrcoef(tica4_all_traj,si5_all_traj_cos)
tica4_CR_si6_cos = np.corrcoef(tica4_all_traj,si6_all_traj_cos)
tica4_CR_si7_cos = np.corrcoef(tica4_all_traj,si7_all_traj_cos)
tica4_CR_si8_cos = np.corrcoef(tica4_all_traj,si8_all_traj_cos)
tica4_CR_si9_cos = np.corrcoef(tica4_all_traj,si9_all_traj_cos)


Correlation_Score_tica4_si = np.zeros((9,1))
Correlation_Score_tica4_si[0,0] = np.abs(tica4_CR_si1_cos[0,1]) + np.abs(tica4_CR_si1_sin[0,1])
Correlation_Score_tica4_si[1,0] = np.abs(tica4_CR_si2_cos[0,1]) + np.abs(tica4_CR_si2_sin[0,1])
Correlation_Score_tica4_si[2,0] = np.abs(tica4_CR_si3_cos[0,1]) + np.abs(tica4_CR_si3_sin[0,1])
Correlation_Score_tica4_si[3,0] = np.abs(tica4_CR_si4_cos[0,1]) + np.abs(tica4_CR_si4_sin[0,1])
Correlation_Score_tica4_si[4,0] = np.abs(tica4_CR_si5_cos[0,1]) + np.abs(tica4_CR_si5_sin[0,1])
Correlation_Score_tica4_si[5,0] = np.abs(tica4_CR_si6_cos[0,1]) + np.abs(tica4_CR_si6_sin[0,1])
Correlation_Score_tica4_si[6,0] = np.abs(tica4_CR_si7_cos[0,1]) + np.abs(tica4_CR_si7_sin[0,1])
Correlation_Score_tica4_si[7,0] = np.abs(tica4_CR_si8_cos[0,1]) + np.abs(tica4_CR_si8_sin[0,1])
Correlation_Score_tica4_si[8,0] = np.abs(tica4_CR_si9_cos[0,1]) + np.abs(tica4_CR_si9_sin[0,1])

In [35]:
print(Correlation_Score_tica1_si[:,0])

[0.26977169 0.26953212 0.0897338  1.07754125 0.87940289 0.58528877
 0.27776795 0.02737757 0.06349432]


In [36]:
print(Correlation_Score_tica2_si)

[[0.28209284]
 [0.50264566]
 [0.02177119]
 [0.25101133]
 [0.83445682]
 [0.45260586]
 [0.0934323 ]
 [0.10320187]
 [0.14997663]]


In [38]:
print(Correlation_Score_tica2 + Correlation_Score_tica1)

[[0.2167029 ]
 [0.36165063]
 [0.58214446]
 [0.64497558]
 [0.16680983]
 [0.39103994]
 [0.15484616]
 [0.06289434]
 [0.07770509]]


In [ ]:
print(Correlation_Score_tica3_si)

In [ ]:
print(Correlation_Score_tica4_si)

In [ ]:
import numpy as np
delta_delta_F = [ 1.4318905 , -9.05675749, -2.76302572, -3.60076012, -0.03739514,
        2.00005859, -1.18727246, -6.79608942, -5.44399137, -1.3625668 ,
        0.8025274 ]
CS_phi = [ 0.06437967, 0.24489582, 0.5014504,  0.27972149, 0.02369518, 0.1708882, 0.1708882,
        0.07400696, 0.02587254, 0.06086136]
CS_phi_new = np.zeros(11)
i = 0
CS_phi_new[0] = CS_phi[0]/2
CS_phi_new[10] = -CS_phi[9]/2
while(i<9):
    CS_phi_new[i+1] = (CS_phi[i+1]+CS_phi[i])/2
    i = i +1
CS_psi = [0.26977169, 0.26953212, 0.0897338,  1.07754125, 0.87940289, 0.58528877,
 0.27776795, 0.27776795, 0.02737757, 0.06349432]


In [ ]:
print(CS_phi_new)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(CS_phi_new,delta_delta_F)

In [ ]:
print(len(CS_phi))

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(CS_phi,delta_delta_F[:-1])

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(CS_psi,delta_delta_F[:-1])

In [39]:
print(Correlation_Score_tica1_si+Correlation_Score_tica2_si)

[[0.55186452]
 [0.77217778]
 [0.11150499]
 [1.32855258]
 [1.71385972]
 [1.03789464]
 [0.37120025]
 [0.13057943]
 [0.21347095]]
